# Generated by Django 4.2.6 on 2023-10-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_community_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='identifier',
            field=models.CharField(default='', max_length=900, unique=True),
        ),
    ]
