# Generated by Django 4.2.6 on 2023-10-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userextended_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='communities',
            field=models.ManyToManyField(related_name='users', to='backend.community'),
        ),
    ]
