# Generated by Django 4.2.6 on 2023-10-27 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0008_alter_membership_community_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(through='backend.Membership', to='backend.userextended'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.userextended'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='identifier',
            field=models.CharField(default='', max_length=900, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
