# Generated by Django 4.2.6 on 2023-10-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_community_members_alter_membership_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
        migrations.AlterField(
            model_name='userextended',
            name='communities',
            field=models.ManyToManyField(related_name='members', to='backend.community'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
