# Generated by Django 4.2.6 on 2023-10-27 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0010_remove_community_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='identifier',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
