# Generated by Django 4.1.1 on 2023-11-12 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_alter_userextended_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userextended",
            name="strava_key",
        ),
    ]
